#!/usr/bin/env bash
#comment hehe
while IFS= read -r line; do
    username=$(echo "$line" | cut -d: -f1)
    GROUP_ID=$(echo "$line" | cut -d: -f4)
    HOME_DIRECTORY=$(echo "$line" | cut -d: -f6)
    USER_ID=$(echo "$line" | cut -d: -f3)  # Fixed space
    USER_ID_INFO=$(echo "$line" | cut -d: -f5)
    COMMAND_SHELL=$(echo "$line" | cut -d: -f7)
    PASSWORD=$(echo "$line" | cut -d: -f2)

    echo "The user $username is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
#!/usr/bin/env bash

#while IFS=: read -r username password user_id group_id user_info home_dir shell; do
 #   echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
#done < /etc/passwd

